using System;
public enum UI_TYPE
{
    UI_MAINPANEL,
    UI_FRIENDLY_ACTOR_LIST_PANEL,
    UI_ENEMY_ACTOR_LIST_PANEL,
    UI_BOSS_ACTOR_LIST_PANEL,
    UI_START_BUTTON,
    UI_BACK_BUTTON,
    UI_FRIENDLY_ACTOR_LIST_BUTTON
    UI_ENEMY_ACTOR_LIST_BUTTON
    UI_BOSS_ACTOR_LIST_BUTTON
}
